version: '3'

services:
  webapi:
    container_name: chatbot.webapi
    build: ./webapi
    ports:
      - "3000:3000"
    volumes:
      - "./todotask.webapi:/usr/src/app"
    environment:
      - NODE_ENV=docker
  web:
    container_name: chatbot.web
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - webapi
    links:
      - webapi