version: '3'

services:
  webapi:
    container_name: chatbot.webapi
    build: ./webapi
    ports:
      - "3000:3000"
  web:
    container_name: chatbot.web
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - webapi
    links:
      - webapi